Section-3 55-58
seanho96/crud-operations pull request #2
Opened 2021-11-08 06:33 UTC by seanho96

- https://trello.com/c/uOucEvJg
- Display hello world through basic MVC pattern

2021-11-08 06:35 UTC, tlkiong requested changes

2021-11-08 06:35 UTC, tlkiong commented on app/controllers/pages_controller.rb
> +    end
2 spaces indent pls

2021-11-09 05:46 UTC, seanho96 commented
The prettier plugin here will be overridden by Rubocop in PR #3.

2021-11-09 12:15 UTC, tlkiong requested changes
Pay attention to details.
Always double, triple check your work.

> To create a masterpiece, you must first care for the details

2021-11-09 12:15 UTC, tlkiong commented on .prettierrc
> +    "rubySingleQuote": false,
Indentation?

2021-11-10 01:12 UTC, seanho96 commented on .prettierrc
> +    "rubySingleQuote": false,
My bad, overlooked this 😓

2021-11-10 02:07 UTC, tlkiong approved these changes

2021-11-10 02:29 UTC, merged